### ISSUE TITLE
What about fixed height ktd-grid and resize within each item?

### ISSUE THREAD

**Issue by irustm** [katoid/angular-grid-layout#1]
Like `Grid Types`= `fit` in gridster https://tiberiuzuld.github.io/angular-gridster2/gridTypes?

**Comment by llorenspujol** [comment]
It's a good feature, simple to add and aligned with the project philosophy. Said that, in this grid solution there is no 'grid type', there are just `cols` and `rowHeight`. Cols fit by default, because is a relative value, but not `rowHeight`.

We should maybe allow the user to put another value in `rowHeight` that are not CSS pixels, for example `rowHeight = 'fit'`. This would work and would make the grid layout fit in it's space. There is also the possibility to make `rowHeight` optional and if not provided just fit, but I am more with the first one.

What are your thoughts? @irustm

**Comment by irustm** [comment]
`rowHeight = 'fit'` Looks good)

**Comment by andrewpolemeni** [comment]
@llorenspujol I was taking a look into this library and rowHeight = 'fit' is a requirement since our layout uses css grid. It would be really helpful and a great feature if you implemented this since other libraries don't have this.

**Comment by llorenspujol** [comment]
@andrewpolemeni The feature itself doesn't require much changes in the code, since it just changes how the rowHeight is calculated. Said that, I tested it a little bit, and I find it a little confusing compared to the current grid purpose.

I would like to know your exact use case, do you expect `rowHeight = 'fit'` to work equal like gridster2 `Grid Types= fit`? You can test it here: https://tiberiuzuld.github.io/angular-gridster2/gridTypes

Right now with the small test I did, it does so, works like in gridster2. But as I said, I found it a bit of an edge case. The fact that a grid item rezise or move can make all other grid items to change its size is a strange behavior IMO. So, would be nice to know your use case more detailed, and see if `rowHeight = 'fit'` can be finally included and how.
