### ISSUE TITLE
Angular 16 support to use standalone component and signals

### ISSUE THREAD

**Issue by sheikalthaf** [katoid/angular-grid-layout#101]
Do you have any plan to update to angular 16, so that we can make use of Standalone components and signals.

I'm ready to raise a PR for this

**Comment by llorenspujol** [comment]
Hi again @sheikalthaf !

Currently, there are no plans to update to Angular 16. 
This is primarily because AFAIK, if we upgrade to Angular 16, users still with Angular 14 will not be able to use the latest version of this lib! But, staying in Angular 14, let's users from Angular 14 to Angular 16 use it perfectly.

That being said, if Angular 14 libraries are not compatible with Angular 17 (which is expected to be released soon), we may need to upgrade the Angular version to ensure the library's compatibility with Angular 17.

**Comment by sheikalthaf** [comment]
Yes, then we can wait for Angular 17 update

**Comment by Jeredian** [comment]
Hi, @llorenspujol 
Are there any updates regarding Angular 17 support ?

**Comment by llorenspujol** [comment]
@Jeredian Agreed, it is time to upgrade Angular Grid Layout to Angular 16 and export it as a standalone component. This way, full standalone apps can import AngularGridLayout.

Having said that, even though Angular Grid Layout is currently written with Angular 14, it remains compatible with Angular 17, as far as you import it into an NgModule.

In resume, I am open to PRs for upgrading to Angular 16 (not Angular 17), with Angular Grid Layout exported as a standalone component. You may want to take it @sheikalthaf

**Comment by devglrd** [comment]
@llorenspujol Did you have open the PRs ?

**Comment by jelle-ingambh** [comment]
Is anything planned regarding Angular 16 / 17 / 18?

**Comment by sheikalthaf** [comment]
> @Jeredian Agreed, it is time to upgrade Angular Grid Layout to Angular 16 and export it as a standalone component. This way, full standalone apps can import AngularGridLayout.
> 
> Having said that, even though Angular Grid Layout is currently written with Angular 14, it remains compatible with Angular 17, as far as you import it into an NgModule.
> 
> In resume, I am open to PRs for upgrading to Angular 16 (not Angular 17), with Angular Grid Layout exported as a standalone component. You may want to take it @sheikalthaf

Created the PR for v15 and v16 versions

**Comment by llorenspujol** [comment]
Release with Angular 16 support is available: https://github.com/katoid/angular-grid-layout/releases/tag/v3.0.0
