### ISSUE TITLE
Updating layout

### ISSUE THREAD

**Issue by Loevbo** [katoid/angular-grid-layout#20]
I'm using this combined with angular 12, and currently it works good but found 1 small problem

> public layout: KtdGridLayout = [
>     { id: '0', x: 0, y: 0, w: 3, h: 3 },
>     { id: '1', x: 3, y: 0, w: 3, h: 3 },
>     { id: '2', x: 0, y: 3, w: 3, h: 3 },
>     { id: '3', x: 3, y: 3, w: 3, h: 3 },
>   ];

When I then try to add another box like `this.layout.push({ id: '4', x: 0, y: 12, w: 3, h: 3 })` it comes with these erros:

![image](https://user-images.githubusercontent.com/26703595/131453830-e35c27b4-1747-407d-a938-3742be4c52fa.png)

Can this be fixed fairly simple

**Comment by llorenspujol** [comment]
The solution to this error is **never mutating the array**. It is exposed on the [Troubleshoot](https://github.com/katoid/angular-grid-layout#troubleshooting) section, although is complicated to see sometimes, here is what it says:

_Mutating the layout would cause an error like: 'ERROR TypeError: Cannot read property 'id' of undefined'. Never mutate the layout, always return a new instance when modifying it._

This is mainly because the Grid needs to know when the layout has changed, and the only way to do it now is just returning a new instance of the array every time it changes.

You can replace 'push' for this code (for example):
`this.layout = [...this.layout, { id: '4', x: 0, y: 12, w: 3, h: 3 }];`

**Comment by Loevbo** [comment]
Thanks for your response. I didn't noticed the troubleshoot section (my bad).

When I run the code you provide it updates the array without any error's but the grid is not updated with the new item. Ready your troubleshoot section, I've also tried removing `trackBy` to make angular update but no lucl

**Comment by llorenspujol** [comment]
Have you checked that it is not a change detection issue? Maybe you are running the `addItem()` outside the zone. To check that, add an item, and after that, make a simple drag on some other grid item, does the item appear? If so, is a change detection issue.

If the above reproduction doesn't make your item appear, you would need to make a stackblitz reproduction of your issue, or provide more information about your code and context to see other possible sources of the error.
