### ISSUE TITLE
Newly added items on 2nd row started from right. It should be from left side.

### ISSUE THREAD

**Issue by sw-ms-surendrasinhrathod** [katoid/angular-grid-layout#21]
When I add new items, from the 2nd row it adding new boxes from the right side. The left side space remains empty always. Please check attached screenshot

![image](https://user-images.githubusercontent.com/32195107/132219414-e3e81c8f-300b-4945-9db0-84c8a621d46d.png)

**Comment by llorenspujol** [comment]
Thanks for reporting!

I have checked the code, and the `compact` function with `compactType='horizontal'` does not handle well adding items the way is done in this example (at position 0, 0), and this is because the bug appears. I think compaction should resolve as you showed in the image so I marked it as a bug.

If you are interested on resolving it you can make a Pull Request (I can guide you a little bit on which code to change if needed). If not don't worry, it would be done in the near future.

**Comment by AntoninoBonanno** [comment]
Hi, any update? 
I have the same problem

**Comment by llorenspujol** [comment]
In the next published version this issue should be solved. Also many changes and fixes for compact 'horizontal' method, that was clearly behaving strange in many situations. Still may need more work, but it is far better right now IMO.
