### ISSUE TITLE
question and feature request

### ISSUE THREAD

**Issue by MinhTuan18** [katoid/angular-grid-layout#47]
1. Is it possible to add new item by drag & drop from outside?
For example from react-grid-layout: https://react-grid-layout.github.io/react-grid-layout/examples/15-drag-from-outside.html
2. How to setting grid gaps?

**Comment by llorenspujol** [comment]
1. Is not possible right now, but since many people are requesting it, I hope it would be possible in some time from now, but can't assure. It's just a matter of time an priorities.

2. It is also not in the API setting grid gaps right now, you can check some workarounds here:  https://github.com/katoid/angular-grid-layout/discussions/43

**Comment by llorenspujol** [comment]
@MinhTuan18 Can you open 2 features for each one of those? since tracking would be easier, and people may vote for them to be done or not.

**Comment by llorenspujol** [comment]
Closing issue since:

- Grid gaps are available since version 2.0.0.
- And the drag & drop from outside, or between grids, it would be tracked on this issue: https://github.com/katoid/angular-grid-layout/issues/50
