### ISSUE TITLE
NullInjectorError: StaticInjectorError(RootModule)[KtdGridItemComponent -> KtdGridService]

### ISSUE THREAD

**Issue by webliuxiang** [katoid/angular-grid-layout#7]
add to my project , but report Error 
![image](https://user-images.githubusercontent.com/25944130/114818630-b044ac80-9dee-11eb-8824-cb7c0739f724.png)

**Comment by webliuxiang** [comment]
@llorenspujol

**Comment by llorenspujol** [comment]
Seems that KtdGridService is not detected by Angular somehow, and when it needs to be provided it just fails. Is strange since KtdGridService has the `provideIn: 'root`', that theoretically, should make it able to be injected when needed even not provided directly to any module, but there has to be something that prevents it (Maybe it gets tree-shaked).

I will check it briefly.

PD: I you want to speed up the process, you can create and stackblitz project reproducing the bug.

**Comment by AsjadMahmood** [comment]
Hey guys, getting the exact same problem,
any solution regarding this issue till now, my angular version = 8.1.2

**Comment by webliuxiang** [comment]
Upgrade angular to 9. X
