### ISSUE TITLE
newly added item always gives itself a different position in a specific scenario

### ISSUE THREAD

**Issue by Rubiniuz** [katoid/angular-grid-layout#73]
I have a small issue with the ktd grid for angular which might be an intended feature.

So my current school and work project uses the premade functions from the stackblitz example for adding and removing ktdGridLayoutItems. I only seem to get a single issue with this code.

Let me first explain the situation. I am using the grid to make a multi-purpose interactive calendar.
so the grid will be a (hours * quarters = 36) Y height and a day's (Monday to Sunday+ time placement = 8) X width.

So I generate my grid row by row the calculated id is what you see in the grid elements.

![image](https://user-images.githubusercontent.com/8469612/212105837-229f8eae-d40f-41b9-a388-5d7bc2cd6d31.png)

If I add and remove 6 height worth of items on the y = 0 and y = 1 everything works fine.
But when doing the same on any y position higher than 0 or 1 it automatically adds 1 to the given y value. 

Here the prompt asks for the height of the element I want to push at the clicked location. 
I start adding an item at x 5 and y 3 with a height of 4. It successfully removes 4 elements and then adds a 4 high item in its place 

![image (1)](https://user-images.githubusercontent.com/8469612/212106572-fdccf9e2-d5e3-49f5-a804-f7daeb00228f.png)

everything looks good. But the Data isn't.
![result](https://user-images.githubusercontent.com/8469612/212107276-59819373-3492-4781-95cb-6a06fe73db8f.png)

Now the logs say the given y pos is still 3(This is the y position of the initial element I choose to replace). But when I open the actual objects I see it's suddenly 4. Where did this change come from?
![console-givenobject-changedobject-givenYpos](https://user-images.githubusercontent.com/8469612/212107857-019fab08-6377-4f22-b5ba-96c4f1a7fd2f.png)

Is this the intended automatic placement of the grid? or is this a weird code bug? See underneath for the code. and the values used.
do note the extra ktdlayout-gridlist is for checking purposes

Remove Item
![image](https://user-images.githubusercontent.com/8469612/212109561-24c61a6e-02fd-407c-9e09-d376f7d9887f.png)

Add Item
![image](https://user-images.githubusercontent.com/8469612/212109381-91f7b883-79a9-49c1-95fd-a645ff0a2c0e.png)

Generate layout
![image](https://user-images.githubusercontent.com/8469612/212109692-815bf24c-9868-4850-bb7b-3ed1759819cc.png)
where cols = 8
and rows = 36

html
![image](https://user-images.githubusercontent.com/8469612/212110094-3f713467-45ea-464e-ad06-6da64cc089e7.png)

values:
Starting pos: X:5 Y:3 W:1 H:1
Element to be placed on starting pos: X5: Y:3 W:1 H:4
All values are copied over except for the height which is replaced by the user prompt and checked for typing.
After the elements get removed the new item gets added. And shows the correct data.
But further opening the object in the log you will see the y value has suddenly risen to 4.
This happens everywhere except for y=0 and y=1

[layout.txt](https://github.com/katoid/angular-grid-layout/files/10403212/layout.txt)

the layout can also be generated via the above code do note this layout does not include my added elements for hours and days definitions

**Comment by amanosacrous** [comment]
Hi @Rubiniuz,

It seems that the problem is related to how the grid has been declared.

I tested the posted code, and the functions for adding and deleting items work perfectly.

On the other hand, in the declaration of the layout, it's curious how the x and y indices are assigned. You declare the headers with hours and weekdays, and for the weekdays, you assign 2 Y spaces. However, when you declare all the other layout items, you start at the position x+1 (correct) and y+1 (incorrect), because you've already used 2 spaces. This causes the Y indices to be off by 1 from the correct ones. I tested it, and it seems to be the key issue.

I drew the grid with this fix, putting the correct indices, and the result is as follows:
![image](https://github.com/katoid/angular-grid-layout/assets/86300428/d8369f3a-6ba4-4be2-a58a-8cb5935d03cd)

As you can see, the real index for ID: 35 is (x: 5, y: 4) because the items in the first row take up 2 spaces. By changing y+1 to y+2 and correcting the left-side header indices in the layout generation, the problem of the inconsistent indices should be fixed.

If this solution does not fix the problem, please provide a StackBlitz reproduction of the bug, and we will investigate further.

**Comment by Rubiniuz** [comment]
@amanosacrous I just tested it and this was the fix. such a small stupid thing I looked over. I updated it and everything is now perfect in my app. thanks for your help
